/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all events */
    get: operations["listEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Ticketmaster: {
      _embedded: {
        events: components["schemas"]["Event"][];
      };
      page: {
        size: number;
        totalElements: number;
        totalPages: number;
        number: number;
      };
    };
    Event: {
      dates: components["schemas"]["Dates"];
      _embedded: components["schemas"]["EventEmbedded"];
      id: string;
      images: components["schemas"]["Image"][];
      name: string;
      url: string;
    };
    EventEmbedded: {
      attractions: components["schemas"]["Attraction"][];
      venues: components["schemas"]["Venue"][];
    };
    Attraction: {
      classifications: components["schemas"]["Classification"][];
      id: string;
      images: components["schemas"]["Image"][];
      locale: string;
      name: string;
      test: boolean;
      type: string;
      url: string;
    };
    Classification: {
      genre: components["schemas"]["IdName"];
      family: boolean;
      primary: boolean;
      segment: components["schemas"]["IdName"];
      subgenre: components["schemas"]["IdName"];
      subtype: components["schemas"]["IdName"];
      type: components["schemas"]["IdName"];
    };
    IdName: {
      id: string;
      name: string;
    };
    Venue: {
      address: {
        line1: string;
      };
      city: {
        name: string;
      };
      country: {
        countryCode: string;
        name: string;
      };
      id: string;
      locale: string;
      location: {
        latitude: string;
        longitude: string;
      };
      name: string;
      postalCode: string;
      state: {
        country: components["schemas"]["Country"];
      };
      test: boolean;
      timezone: string;
      type: string;
      url: string;
    };
    Country: {
      countryCode: string;
      name: string;
    };
    Dates: {
      start: {
        dateTBA: boolean;
        dateTBD: boolean;
        /** Format: date-time */
        dateTime: string;
        /** Format: date */
        localDate: string;
        localTime: string;
        noSpecificTime: boolean;
        timeTBA: boolean;
      };
    };
    Image: {
      fallback: boolean;
      height: number;
      width: number;
      ratio: string;
      url: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listEvents: {
    parameters: {
      query?: {
        /** @description Filter events by attraction ID */
        attractionId?: string;
        /** @description Filter events by classification name */
        classificationName?: string;
        /** @description Filter events by country code */
        countryCode?: string;
        /** @description Filter events by locale */
        locale?: string;
        /** @description Filter events by city */
        city?: string;
        /** @description Filter events starting from this date and time */
        startDateTime?: string;
        /** @description Filter events ending by this date and time */
        endDateTime?: string;
        /** @description Sort order of the events */
        sort?: string;
        /** @description Filter events by genre ID */
        genreId?: string;
        /** @description Page number for pagination */
        page?: string;
        /** @description Number of items per page */
        size?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ticketmaster"];
        };
      };
    };
  };
}
