// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package model

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Attraction defines model for Attraction.
type Attraction struct {
	Classifications []Classification `json:"classifications"`
	Id              string           `json:"id"`
	Images          []Image          `json:"images"`
	Locale          string           `json:"locale"`
	Name            string           `json:"name"`
	Test            bool             `json:"test"`
	Type            string           `json:"type"`
	Url             string           `json:"url"`
}

// Classification defines model for Classification.
type Classification struct {
	Family   bool   `json:"family"`
	Genre    IdName `json:"genre"`
	Primary  bool   `json:"primary"`
	Segment  IdName `json:"segment"`
	Subgenre IdName `json:"subgenre"`
	Subtype  IdName `json:"subtype"`
	Type     IdName `json:"type"`
}

// Country defines model for Country.
type Country struct {
	CountryCode string `json:"countryCode"`
	Name        string `json:"name"`
}

// Dates defines model for Dates.
type Dates struct {
	Start struct {
		DateTBA        bool               `json:"dateTBA"`
		DateTBD        bool               `json:"dateTBD"`
		DateTime       time.Time          `json:"dateTime"`
		LocalDate      openapi_types.Date `json:"localDate"`
		LocalTime      string             `json:"localTime"`
		NoSpecificTime bool               `json:"noSpecificTime"`
		TimeTBA        bool               `json:"timeTBA"`
	} `json:"start"`
}

// Event defines model for Event.
type Event struct {
	UnderscoreEmbedded EventEmbedded `json:"_embedded"`
	Dates              Dates         `json:"dates"`
	Id                 string        `json:"id"`
	Images             []Image       `json:"images"`
	Name               string        `json:"name"`
	Url                string        `json:"url"`
}

// EventEmbedded defines model for EventEmbedded.
type EventEmbedded struct {
	Attractions []Attraction `json:"attractions"`
	Venues      []Venue      `json:"venues"`
}

// IdName defines model for IdName.
type IdName struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// Image defines model for Image.
type Image struct {
	Fallback bool   `json:"fallback"`
	Height   int    `json:"height"`
	Ratio    string `json:"ratio"`
	Url      string `json:"url"`
	Width    int    `json:"width"`
}

// Ticketmaster defines model for Ticketmaster.
type Ticketmaster struct {
	UnderscoreEmbedded struct {
		Events []Event `json:"events"`
	} `json:"_embedded"`
	Page struct {
		Number        int `json:"number"`
		Size          int `json:"size"`
		TotalElements int `json:"totalElements"`
		TotalPages    int `json:"totalPages"`
	} `json:"page"`
}

// Venue defines model for Venue.
type Venue struct {
	Address struct {
		Line1 string `json:"line1"`
	} `json:"address"`
	City struct {
		Name string `json:"name"`
	} `json:"city"`
	Country struct {
		CountryCode string `json:"countryCode"`
		Name        string `json:"name"`
	} `json:"country"`
	Id       string `json:"id"`
	Locale   string `json:"locale"`
	Location struct {
		Latitude  string `json:"latitude"`
		Longitude string `json:"longitude"`
	} `json:"location"`
	Name       string `json:"name"`
	PostalCode string `json:"postalCode"`
	State      struct {
		Country Country `json:"country"`
	} `json:"state"`
	Test     bool   `json:"test"`
	Timezone string `json:"timezone"`
	Type     string `json:"type"`
	Url      string `json:"url"`
}

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	// AttractionId Filter events by attraction ID
	AttractionId *string `form:"attractionId,omitempty" json:"attractionId,omitempty"`

	// ClassificationName Filter events by classification name
	ClassificationName *string `form:"classificationName,omitempty" json:"classificationName,omitempty"`

	// CountryCode Filter events by country code
	CountryCode *string `form:"countryCode,omitempty" json:"countryCode,omitempty"`

	// Locale Filter events by locale
	Locale *string `form:"locale,omitempty" json:"locale,omitempty"`

	// City Filter events by city
	City *string `form:"city,omitempty" json:"city,omitempty"`

	// StartDateTime Filter events starting from this date and time
	StartDateTime *time.Time `form:"startDateTime,omitempty" json:"startDateTime,omitempty"`

	// EndDateTime Filter events ending by this date and time
	EndDateTime *time.Time `form:"endDateTime,omitempty" json:"endDateTime,omitempty"`

	// Sort Sort order of the events
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// GenreId Filter events by genre ID
	GenreId *string `form:"genreId,omitempty" json:"genreId,omitempty"`

	// Page Page number for pagination
	Page *string `form:"page,omitempty" json:"page,omitempty"`

	// Size Number of items per page
	Size *string `form:"size,omitempty" json:"size,omitempty"`
}
