export enum Genre {
  Alternative = "KnvZfZ7vAvv",
  Blues = "KnvZfZ7vAvd",
  "Children's Music" = "KnvZfZ7vAvk",
  Classical = "KnvZfZ7vAeJ",
  Country = "KnvZfZ7vAv6",
  "Dance/Electronic" = "KnvZfZ7vAvF",
  Folk = "KnvZfZ7vAva",
  "Hip-Hop/Rap" = "KnvZfZ7vAv1",
  Metal = "KnvZfZ7vAvt",
  "New Age" = "KnvZfZ7vAvn",
  Other = "KnvZfZ7vAvl",
  Pop = "KnvZfZ7vAev",
  Reggae = "KnvZfZ7vAed",
  Religious = "KnvZfZ7vAe7",
  Rock = "KnvZfZ7vAeA",
  "R&B" = "KnvZfZ7vAee",
  World = "KnvZfZ7vAeF",
}
