import type { Metadata } from "next";
import { Reddit_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const redditMono = Reddit_Mono({
  variable: "--font-reddit-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${redditMono.variable} font-mono antialiased dark`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
